### ISSUE TITLE
Max Payload Size is undocumented?

### ISSUE THREAD

**Issue by zachstronaut** [Unity-Technologies/com.unity.multiplayer.docs#1111]
Unity Transport's Max Payload Size has no supporting documentation that I can find.

I have a Netcode for GameObjects scene that was failing to load with the error: "Couldn't add payload of size 17135 to reliable send queue. Closing connection 1 as reliability guarantees can't be maintained." This is with the default Max Payload Size of 6144.

I was able to increase this value to avoid the issue, but I'm unclear on the consequences of increasing this max payload and what reasonable upper limits are.

**Comment by zachstronaut** [comment]
@NoelStephensUnity Helpful, thank you!

I believe Unity Transport 1.4.0 has a default InitialMaxPayloadSize = 6 * 1024; ... which is TINY. I was able to fix my problems going to 24K so hearing you say that I could set it even larger than that makes me feel a lot better.

**Comment by simon-lemay-unity** [comment]
> I believe Unity Transport 1.4.0 has a default InitialMaxPayloadSize = 6 * 1024; ... which is TINY. I was able to fix my problems going to 24K so hearing you say that I could set it even larger than that makes me feel a lot better.

I agree that the default maximum payload size is pretty small, but one thing to note is that _reliable_ messages can go over that value (since version 1.0.1). And most traffic in NGO is reliable. So in practice, that limit doesn't matter all that much. Nowadays it only applies to unreliable traffic (its admittedly limited documentation does mention it).

I'm surprised you encountered that "couldn't add payload to reliable send queue" error. We used to see it a _lot_, but have since addressed that problem. Recent-ish versions of NGO have a dynamically-sized send queue which should handle quite a lot of traffic before hitting that problem. You'd need to have megabytes of pending traffic to see this error now.

**Comment by zachstronaut** [comment]
@simon-lemay-unity The profiler says the Load (my scene) -- Scene Event is the culprit... where all the data comes from.

We're using a patched version of 1.5.1 ... neither 1.5.2 nor 1.6.0 have included some of the patches we rely on, and I am too lazy to re-patch so far.

**Comment by jabbacakes** [comment]
[This PR](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/pull/2877) in the Netcode for GameObjects repo has been merged, so updates to clarify MaxPayloadSize in the API doc will be live with the next package release.
