### ISSUE TITLE
Compiler error in HelloWorldPlayer.cs (docs/tutorials/get-started-with-ngo.md)

### ISSUE THREAD

**Issue by Hemaolle** [Unity-Technologies/com.unity.multiplayer.docs#1186]
When I add the `HelloWorldPlayer.cs` code on the documentation page `docs/tutorials/get-started-with-ngo.md` I get the following compiler error (Unity 2022.3.18f1, `com.unity.netcode.gameobjects` package version 1.8.0)

```
Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP: (0,0): error  - Only ServerRpcs may accept ServerRpcParams as a parameter.
```

sounds like it's related to this function:

```
[Rpc(SendTo.Server)]
void SubmitPositionRequestServerRpc(ServerRpcParams rpcParams = default)
{
    var randomPosition = GetRandomPositionOnPlane();
    transform.position = randomPosition;
    Position.Value = randomPosition;
}
```

**Comment by jabbacakes** [comment]
This has been fixed in a recent update! The introduction of the new universal [RPC parameter](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/message-system/rpc/) also saw the deprecation of the old `ServerRpcParams`, and we missed updating this example from `ServerRpcParams` ---> `RpcParams`.
