### ISSUE TITLE
Error Occur in HelloWorldPlayer class in Page of "Get Start with NGO" [1.8.0]

### ISSUE THREAD

**Issue by joe2275** [Unity-Technologies/com.unity.multiplayer.docs#1190]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP: (0,0): error  - Only ServerRpcs may accept ServerRpcParams as a parameter.

When you erase "ServerRpcParams" parameter of "SubmitPositionRequestServerRpc" function, this error will not occur. 

**Steps to reproduce the behavior:**
1. Go to "Get Start with NGO" Page.
2. Copy and Paste HelloWorldPlayer class.
3. See Error.

This error message doesn't make it clear where in the script the error is occurring, so it would be nice to fix this page.

**Comment by jabbacakes** [comment]
This has been fixed in a recent update! The introduction of the new universal [RPC parameter](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/message-system/rpc/) also saw the deprecation of the old `ServerRpcParams`, and we missed updating this example from `ServerRpcParams` ---> `RpcParams`.
