### ISSUE TITLE
Outdated guide

### ISSUE THREAD

**Issue by Awaken-01** [Unity-Technologies/com.unity.multiplayer.docs#1191]
Compilation errors.

**Comment by jabbacakes** [comment]
This has been fixed in a recent update! The introduction of the new universal [RPC parameter](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/message-system/rpc/) also saw the deprecation of the old `ServerRpcParams`, and we missed updating this example from `ServerRpcParams` ---> `RpcParams`.
