### ISSUE TITLE
Feedback for docs/tutorials/get-started-with-ngo.md

### ISSUE THREAD

**Issue by Moosemorals** [Unity-Technologies/com.unity.multiplayer.docs#1309]
In section https://docs-multiplayer.unity3d.com/netcode/current/tutorials/get-started-ngo/#the-helloworldmanagercs-script, static method `StartButtons()` tries to access the (class) field `m_NetworkManager` which gives a "Cannot access non-static field in static context" error in Rider.

Does the method need to be static? I see further down the tutorial there's an option to directly access the singleton `NetworkManager`, would it be better to define `m_NetworkManager` as static?

```csharp
private static NetworkManager m_NetworkManager = NetworkManager.Singleton
```

(and remove the "Awake" method).

I'm just getting started with Unity, so my appologies if I'm just missing something obvious.

**Comment by jabbacakes** [comment]
This issue was resolved in PR #1266, and you can see the updated code example in the 1.10.0 (and 2.0.0-exp) docs: https://docs-multiplayer.unity3d.com/netcode/1.10.0/tutorials/get-started-ngo/#the-helloworldmanagercs-script

I'm going to close this issue as completed, but feel free to open it again if you continue to have issues or need more help ^_^
