### ISSUE TITLE
Feedback for /docs/mlapi-basics/object-ownership.md

### ISSUE THREAD

**Issue by chrispope** [Unity-Technologies/com.unity.multiplayer.docs#15]
Should be sub-chapter of NetworkedObject and it needs improved explanation. What is a player object, and what are ownership and the differences. And then how do I spawn something with Ownership?

**Comment by goudcode** [comment]
There is a method called `SpawnWithOwnership` oon the NetworkObject component that takes in a client id.
Using this will setup the ownership of an object before it gets synced to the clients.

It might be helpful to add documentation for the method on the spawning page as well.

**Comment by bestdani** [comment]
I was just desperately looking for how to give back the ownership to the server when a client (ungracefully) disconnects, I found the `DontDestroyWithOwner` field luckily thanks for VS code completion and then found out by googleing this is actually documented in Object Spawning.

Therefore I would suggest to also mention this in the Ownership section since it affects both ownership and spawning.

**Comment by s-omeilia-unity** [comment]
I don't believe all aspects of this request have been met yet, so worth a (re)visit. Couldn't find a connected Jira ticket before creating a new one.

**Comment by Briancoughlin** [comment]
This is now on the backlog to be done thanks for your contribution

**Comment by s-omeilia-unity** [comment]
Related issues: #206, #470, #481, #512, #515, #555
