### ISSUE TITLE
Search function on multiplayer docs site broken

### ISSUE THREAD

**Issue by foxblock** [Unity-Technologies/com.unity.multiplayer.docs#593]
![grafik](https://user-images.githubusercontent.com/816309/163712962-b0d8c9ef-3fb1-4358-87af-efffb970d3eb.png)
Using the search function on https://docs-multiplayer.unity3d.com/ only generates results to broken pages for me.

Example:
![grafik](https://user-images.githubusercontent.com/816309/163712911-dacb731a-640a-4178-a8ae-5422ac305896.png)
The first results are in order as shown:
https://docs-multiplayer.unity3d.com/docs/basics/networkbehavior/index.html
https://docs-multiplayer.unity3d.com/docs/develop/basics/networkbehavior/index.html
https://docs-multiplayer.unity3d.com/docs/0.1.0/basics/networkbehavior/index.html
https://docs-multiplayer.unity3d.com/docs/develop/basics/networkbehavior/
https://docs-multiplayer.unity3d.com/docs/basics/networkbehavior/
https://docs-multiplayer.unity3d.com/docs/develop/api/Unity.Netcode.NetworkBehaviour/index.html
https://docs-multiplayer.unity3d.com/docs/api/Unity.Netcode.NetworkBehaviour/index.html

All these links are broken and lead to a "page not found".

This seems to be the case for any term I search for.

FWIW the correct link should be
https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.NetworkBehaviour

**Comment by s-omeilia-unity** [comment]
We had an issue with refreshing our indexing but it is now resolved. I tested with this specific search and a handful of others. You may have to use an incognito browser to see the immediate change because of caching (typical with most documentation changes) for the first hour or so after a fix has been put in.

The current issue with the results is that the first result seems to point to the older doc version than the current, but that I'm still working on looking into a fix for that while addressing other doc work. But the second item on the list seems to be the current doc.
