### ISSUE TITLE
Misconception regarding the behaviour of `ref struct`s in `BufferSerializer` documentation

### ISSUE THREAD

**Issue by DaZombieKiller** [Unity-Technologies/com.unity.multiplayer.docs#761]
**Describe the bug:**
The documentation page for [`BufferSerializer`](https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.BufferSerializer-1/) states the following:

> Ref structs help enforce both of those rules: they can't out live the stack context in which they were created, and they're always passed by reference no matter what.

The second part of this statement is entirely untrue. A `ref struct` is not implicitly passed by `ref`, despite the arguably confusing `ref struct` terminology. A `ref struct` will be passed by value just like a regular `struct`, it is merely capable of storing fields of `ref`-like types (such as `Span<T>`) and is thus restricted to the stack to support that.

**Expected behavior:**
The documentation should not be propagating misconceptions regarding language features.

**Screenshots**
![image](https://user-images.githubusercontent.com/6316315/160281663-82f21aac-e97b-4d39-b3bc-f8d0433cda2a.png)

**Additional info:**
I sincerely hope that this is merely a documentation error, and not a misunderstanding that has lead to an incorrect API. If code is expecting these types to be passed by `ref` implicitly, there is potentially a lot of subtly broken behaviour within the library.

**Comment by armstrongl** [comment]
Hi @DaZombieKiller! Thanks for reporting this issue. I'll remove the misleading statement from the documentation as a short-term fix in #938. However, since the SDK documentation is generated from the code, I'll also sync with the team to ensure (A) this gets removed and (B) that this is only a documentation issue.

**Comment by ShadauxCat** [comment]
You are correct! Fortunately this is just a documentation error... we actually realized this was an issue before this ever got published and I just forgot to update the documentation.

The underlying structures (FastBufferReader and FastBufferWriter) are implemented as structs that contain pointers, so while, yes, they are "copied" when they get passed around, all that gets copied is the pointer address. At a higher level, the FBR/FBW that's used by BufferSerializer is an IDisposable within a `using` block - so the reason BufferSerializer is still a ref struct is to prevent anyone trying to store it for reuse later outside of that block, because if they do, it'll be pointing at an already-freed pointer.

I'll make sure the documentation gets updated in the next release.
