### ISSUE TITLE
Link doesn't exist ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by docdact** [Unity-Technologies/com.unity.multiplayer.docs#822]
The Link: [Testing the command line helper](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/goldenpath_series/goldenpath_two/index.html#testing-the-command-line-helper)

doesn't work.

**Comment by Scincy** [comment]
It seems necessary to change to [this link](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld#testing-the-command-line-helper) of the previously placed part of #testing-the-command-line-helper. The reason is that the content user want to move in this article exists in other documents related to the Hello World project.

https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld#testing-the-command-line-helper

**Comment by LPLafontaineB** [comment]
Thank you for reporting this issue, it has now been fixed in our develop branch
